name: "Lint PR title preview (current branch, outputErrorMessage)"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - uses: ./
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Output Error Message
        if: always()
        run: echo '${{ steps.lint_pr_title.outputs.ERROR_MESSAGE }}'
          
